export const media = {
  homeHero: "/images/brand/yes2win-home-hero.webp",
  featuredGames: "/images/brand/yes2win-featured-games.webp",
  responsible: "/images/brand/yes2win-responsible.webp",
  registerJourney: "/images/brand/yes2win-register-journey.webp",
  accountAccess: "/images/brand/yes2win-account-access.webp",
  contactSupport: "/images/brand/yes2win-contact-support.webp",
  aboutEcosystem: "/images/brand/yes2win-about-ecosystem.webp",
  mobileDevice: "/images/brand/yes2win-mobile-device.webp",
  partnerEcosystem: "/images/brand/yes2win-partner-ecosystem.webp",
  partnerTracking: "/images/brand/yes2win-partner-tracking.webp",
  vipHero: "/images/brand/yes2win-vip-hero.webp",
  vipPersonal: "/images/brand/yes2win-vip-personal.webp",
  vipEvents: "/images/brand/yes2win-vip-events.webp",
  categories: {
    slots: "/images/brand/yes2win-games-slots.webp",
    "live-casino": "/images/brand/yes2win-games-live-casino.webp",
    sports: "/images/brand/yes2win-games-sports.webp",
    fishing: "/images/brand/yes2win-games-fishing.webp",
    lottery: "/images/brand/yes2win-games-lottery.webp",
  },
  promotions: {
    welcome: "/images/brand/yes2win-promotion-welcome.webp",
    deposit: "/images/brand/yes2win-promotion-deposit.webp",
    weekly: "/images/brand/yes2win-promotion-weekly.webp",
    cashback: "/images/brand/yes2win-promotion-cashback.webp",
    "vip-benefits": "/images/brand/yes2win-promotion-vip.webp",
    special: "/images/brand/yes2win-promotion-special.webp",
  },
} as const;
